spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 23103890xp..
    url: jdbc:mysql://47.95.221.252:3306/medicine?characterEncoding=utf-8&useSSL=false
    username: root
